version: "3.2"
services:
  neo4j_testing:
    image: neo4j:3.4.5
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:17687
      - NEO4J_dbms_memory_pagecache_size=100M
    ports:
     - "17687:7687"
     - "16479:6479"
     - "17474:7474"
  neo4j_dev:
    image: neo4j:3.4.5
    environment:
      - NEO4J_AUTH=none
    volumes:
      - $HOME/neo4j/data:/data
    ports:
     - "7687:7687"
     - "6479:6479"
     - "7474:7474"
  #elasticsearch_dev:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
  #  environment:
  #    - discovery.type=single-node
  #    - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #  volumes:
  #    - $HOME/elasticsearch/data:/data
  #  ports:
  #    - "9300:9300"
  #    - "9200:9200"
  #files_nginx:
  #  image: nginx:latest
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #    - ./${UPLOAD_FOLDER}/files
  #  ports:
  #    - "8080:80"
#  elija:
#    build: .
#    depends_on:
#      - neo4j_dev
#      - elasticsearch_dev
#    environment:
#      - USE_COMPOSE_ENV=TRUE
#    command: ./wait-for.sh neo4j_dev:7474 --timeout=30 -- ./start-gunicorn.sh
#    volumes:
#      - ./${UPLOAD_FOLDER}:/src/uploads
#    ports:
#      - "5000:5000"
