version: "3"
services:
  neo4j_dev:
    image: neo4j:3.4.5
    environment:
      - NEO4J_AUTH=none
    volumes:
      - $HOME/neo4j/data:/data
    ports:
     - "7687:7687"
     - "7474:7474"
  elasticsearch_dev:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9300:9300"
      - "9200:9200"
  elija:
    build: ..
    image: bp2018hg1/elija:${CIRCLE_WORKFLOW_ID}
    depends_on:
      - neo4j_dev
      - elasticsearch_dev
    environment:
      - USE_COMPOSE_ENV=TRUE
    command: ./wait-for.sh neo4j_dev:7687 --timeout=60 -- ./start-gunicorn.sh
    ports:
      - "5000:5000"
  jona:
    ipc: host # https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772
    image: bp2018hg1/jona_dev:master
    depends_on:
      - elija
    environment:
      - REACT_APP_API_URL=http://elija:5000
      - REACT_APP_GOOGLE_CLIENT_ID=24456970850-u9prmb53vbgthab5qrel3b0rqe7rcjua.apps.googleusercontent.com
      - CYPRESS_API_URL=http://elija:5000
      - CYPRESS_NEO4J_URL=http://:@neo4j_dev:7474
    ports:
      - "3000:3000"
